In [1]:
def a():
    print('a')
def b():
    print('b')
def c(funcs):
    funcs[0]()
    funcs[1]()
funcs = (a,b)
c(funcs)

a
b


In [5]:
class fun:
    def a():
        print('a')
    def b():
        print('b')
    def c():
        funcs = (a,b)
        funcs[0]()
        funcs[1]()

In [4]:
f = fun()
f.c()

TypeError: c() takes 0 positional arguments but 1 was given

In [6]:
f.a()

TypeError: a() takes 0 positional arguments but 1 was given

In [7]:
f = fun()

In [17]:
f.a

<bound method fun.a of <__main__.fun object at 0x7f987cae3588>>

In [9]:
f.type

AttributeError: 'fun' object has no attribute 'type'

In [18]:
import numpy as np
import pandas as pd

In [19]:
x = pd.DataFrame(-1 + 2 * np.random.rand(40, 20)) * 100

In [20]:
x

0          1          2          3          4          5   \
0  -68.336618 -56.516096  40.633495 -23.031899 -66.371961  53.077649   
1  -57.641497  66.747503  87.105139  66.915396 -36.979013 -91.908376   
2   22.655870 -98.540574  56.975050 -45.831969   7.132427  38.719652   
3   20.918457  16.531901  67.319851 -25.808555 -47.597621  41.478751   
4   34.738297  29.133970 -61.506244  42.061419 -92.736071 -75.255823   
5  -42.482519  -1.440097  13.235240  11.496078 -79.964925  81.357164   
6  -94.105100  26.302038  77.329621  74.959068  -6.785726 -12.412094   
7  -91.651437 -66.668659 -25.864092  89.155076   3.993435  98.543219   
8   14.869330 -77.351362 -13.034355  73.276242  -4.347534 -78.894307   
9  -50.022064 -69.382095  52.409701  -3.055785 -14.360841  91.130993   
10  72.094969 -18.962275 -24.879187  -4.244772  33.225345 -18.145580   
11  23.970431  33.320557 -70.040885  85.984921 -70.424670  43.007815   
12   9.785661 -86.665795  10.309316  -2.876845 -46.594140  40.230200   
13  45.817827  -0.532247 -27.283968 -84.533335  35.866489  30.504697   
14  40.300325  93.468146  41.987970  88.257226  86.973341  55.646305   
15 -83.674303 -73.249682  21.474439 -94.350477  -1.333618   3.234357   
16 -18.364276  41.982762 -34.530302  96.267313  66.900154  22.048478   
17  24.864455  64.831240  82.915266 -45.069058  -6.008079  -1.955773   
18 -11.691197  58.841112 -88.333053 -50.853288 -28.335812 -13.140668   
19  -7.826589 -94.253548  28.014795 -48.599436 -14.403828   0.409986   
20 -88.823356  62.538109 -75.341214  36.173742   5.897470  73.922392   
21  -0.542949  85.268802 -43.850299  66.387985  58.016886 -91.997206   
22 -14.963162  23.780843  91.995711  89.055616 -20.479523 -21.209892   
23 -73.189178   6.003966 -29.628514 -68.158276  56.998667 -19.165683   
24 -69.759369  28.545162 -34.523488   0.594504  71.384531  32.499733   
25  65.764914 -74.292247 -95.012591  96.140068 -55.784490 -11.341872   
26  83.573142  19.315609 -86.755242 -28.853432 -72.454901  88.335917   
27 -98.768755  84.177087  99.138463  34.423033   0.049460 -18.948000   
28 -38.324164 -37.289730  23.355723  38.109391  40.626540 -61.904079   
29 -32.085373 -85.886405  27.269948  91.102818 -99.701733  22.800600   
30  49.159374 -43.570489 -77.962618   1.271746 -69.803566  80.151757   
31  -7.222276 -86.548376  93.832315 -22.119839  -9.055035  -0.518771   
32 -56.949446 -28.088149 -35.824765  61.857354 -16.440849  -8.261045   
33 -24.364636 -45.001119 -93.098047  26.421418 -71.940140  51.147883   
34  44.115499 -48.471749  55.885248  54.549840 -75.010067  56.733573   
35 -94.399833 -73.155528  91.739658  21.782165  84.446386 -86.753618   
36 -53.126972 -27.808277 -20.492301 -86.278328 -73.720537 -99.957324   
37  97.673037 -48.930576 -22.417969  31.764479  82.843615 -48.091395   
38 -50.183816 -25.035207  75.058056 -67.579784 -55.591087  52.417859   
39 -17.064719  -9.801660 -97.287790  54.058439 -37.970257  75.230353   

           6          7          8          9          10         11  \
0  -40.006809  74.559225 -48.192007  19.681936  18.444378 -71.190456   
1   -5.243890  54.417059 -20.335050  51.997439 -72.808169 -79.656995   
2   76.485741 -76.571125  24.754570  64.441111  18.760394  10.994528   
3  -49.344975  -2.373734  88.797315  73.561500 -43.990152 -57.893408   
4   82.823934  77.235183  98.933034  49.850778  -8.503941  86.621485   
5   -7.267984 -47.072527 -81.299397 -98.924904   6.258965  72.139130   
6   90.049835  20.546543  80.318348  98.577564  38.824850  85.245737   
7  -77.066253  87.521381  10.475015  50.665972  13.520782  55.225370   
8   27.830131  73.565781 -73.129292 -59.547589  16.807582 -54.381503   
9  -85.666452 -14.590857  80.223635  40.083574  -6.544264  60.626918   
10  -9.141341  -1.504573 -43.042926   3.664696 -58.823694  25.727595   
11  49.185904  12.077386  57.667514  70.183257 -83.035213 -23.689479   
12  12.410858 -25.505258 -97.180638  75.649712 -41.577237 -92.063479   
13 -74.414190 -76.921767 -82.699405  73.901995  24

In [21]:
x.iloc[5]

0    -42.482519
1     -1.440097
2     13.235240
3     11.496078
4    -79.964925
5     81.357164
6     -7.267984
7    -47.072527
8    -81.299397
9    -98.924904
10     6.258965
11    72.139130
12    -6.465674
13   -54.582384
14    98.470188
15    50.365149
16   -69.607354
17    87.805790
18    12.508820
19    40.274243
Name: 5, dtype: float64

In [22]:
x.iloc[0]

0    -68.336618
1    -56.516096
2     40.633495
3    -23.031899
4    -66.371961
5     53.077649
6    -40.006809
7     74.559225
8    -48.192007
9     19.681936
10    18.444378
11   -71.190456
12    10.235460
13    51.310819
14    60.867045
15   -71.661726
16    58.379296
17    -3.023769
18    -2.434941
19    77.549360
Name: 0, dtype: float64

In [23]:
xi = np.zeros(20)
xi = x.iloc[0]

In [24]:
xi

0    -68.336618
1    -56.516096
2     40.633495
3    -23.031899
4    -66.371961
5     53.077649
6    -40.006809
7     74.559225
8    -48.192007
9     19.681936
10    18.444378
11   -71.190456
12    10.235460
13    51.310819
14    60.867045
15   -71.661726
16    58.379296
17    -3.023769
18    -2.434941
19    77.549360
Name: 0, dtype: float64

In [25]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
x.max()

0     97.673037
1     93.468146
2     99.138463
3     96.267313
4     86.973341
5     98.543219
6     98.437725
7     87.521381
8     98.933034
9     98.577564
10    84.639984
11    96.974269
12    99.380867
13    93.253718
14    98.470188
15    89.235346
16    99.979424
17    99.720288
18    89.817219
19    97.709900
dtype: float64

In [27]:
a = np.zeros(5)

In [28]:
a.max()

0.0

In [30]:
a = np.eye(4)

In [31]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
a.max()

1.0

In [33]:
b = pd.DataFrame(a)

In [34]:
b

0    1    2    3
0  1.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0
2  0.0  0.0  1.0  0.0
3  0.0  0.0  0.0  1.0

In [35]:
b.min()


0    0.0
1    0.0
2    0.0
3    0.0
dtype: float64

In [39]:
b.idxmin()

0    1
1    0
2    0
3    0
dtype: int64

In [38]:
b.idxmax

<bound method DataFrame.idxmax of      0    1    2    3
0  1.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0
2  0.0  0.0  1.0  0.0
3  0.0  0.0  0.0  1.0>

In [40]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
b

0    1    2    3
0  1.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0
2  0.0  0.0  1.0  0.0
3  0.0  0.0  0.0  1.0

In [52]:
b.sort_values(by=[1])

0    1    2    3
0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0
3  0.0  0.0  0.0  1.0
1  0.0  1.0  0.0  0.0

In [53]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [54]:
a[0]

array([1., 0., 0., 0.])

In [55]:
b

0    1    2    3
0  1.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0
2  0.0  0.0  1.0  0.0
3  0.0  0.0  0.0  1.0

In [56]:
b[0].sort

AttributeError: 'Series' object has no attribute 'sort'

In [57]:
b[0].sort_values()

1    0.0
2    0.0
3    0.0
0    1.0
Name: 0, dtype: float64

In [58]:
c = np.array([])

In [59]:
c.append('nihao')

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [62]:
np.random.randint?

In [63]:
np.random.sample?


In [64]:
i=0
i++

SyntaxError: invalid syntax (<ipython-input-64-22ce6d6d220d>, line 2)

In [65]:
c

array([], dtype=float64)

In [66]:
c = np.array([1,2,3])

In [67]:
0 % 10

0

In [68]:
c[1:]

array([2, 3])

In [69]:
b

0    1    2    3
0  1.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0
2  0.0  0.0  1.0  0.0
3  0.0  0.0  0.0  1.0

In [70]:
c = b[0]

In [71]:
c

0    1.0
1    0.0
2    0.0
3    0.0
Name: 0, dtype: float64